name: stv-create-zip-release
description: Action to create a release with a ZIP artifact created from the contents of given artifacts

inputs:
  artifacts:
    description: 'A list of file and folder names separated by whitespace'
    required: true

runs:
  using: "composite"
  steps:
  - name: Cleanup Artifact Name
    id: artifact_name
    run: echo "artifact_name=$(echo ${{ github.event.repository.name }}} | sed 's/com_//').zip" >> "$GITHUB_OUTPUT"
  - name: Create Artifact
    run: zip -r ${{ steps.artifact_name.outputs.artifact_name }} ${{ inputs.artifacts }}
  - name: Create Release
    uses: ncipollo/release-action@v1
    with:
      artifacts: ${{ steps.artifact_name.outputs.artifact_name }}
